<a href="https://colab.research.google.com/github/pamela0501/MyPython/blob/main/Tensorflow_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from pprint import pprint

import tensorflow as tf
import numpy as np
a = tf.ones(shape=(2,3), dtype = tf.int32)
a

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 1, 1],
       [1, 1, 1]], dtype=int32)>

In [ ]:
b = tf.constant([[1,2,3],[5,6,7]])
print("b = ", b)

b =  tf.Tensor(
[[1 2 3]
 [5 6 7]], shape=(2, 3), dtype=int32)


In [ ]:
npvar = np.array(["Hello", "World"])
c = tf.constant(npvar)
print("c= ",c)

c=  tf.Tensor([b'Hello' b'World'], shape=(2,), dtype=string)


We can use random initializer

In [ ]:
e = tf.random.normal(shape= [2,3], mean = 0.0, stddev =1.0)
e

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 1.590409  , -1.2654614 ,  0.3007141 ],
       [ 0.4777444 , -0.18830675, -0.39771727]], dtype=float32)>

In [ ]:
w = tf.Variable(20., name = "my_var01")
w

<tf.Variable 'my_var01:0' shape=() dtype=float32, numpy=20.0>